# Generated by Django 4.2.3 on 2023-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
