# Generated by Django 4.2.3 on 2023-07-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_update',
        ),
    ]
