# Generated by Django 4.2.3 on 2023-07-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_nombre_remove_product_category_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nombre',
        ),
    ]
