# Generated by Django 4.2.3 on 2023-07-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_sale_product_remove_ticket_id_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
