# Generated by Django 4.2.3 on 2023-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
