# Generated by Django 4.2.3 on 2023-07-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ticket'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
