# Generated by Django 4.2.3 on 2023-07-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_sale_product_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_update',
        ),
    ]
